import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import type { MoreStackParamList } from './types';
import { MoreScreen } from '../screens/more/MoreScreen';
import { BusinessCenterScreen } from '../screens/more/BusinessCenterScreen';
import { MyBookingsScreen } from '../screens/services/MyBookingsScreen';
import { BookingDetailsScreen } from '../screens/services/BookingDetailsScreen';
import { MyOffersScreen } from '../screens/more/MyOffersScreen';
import { SavedOffersScreen } from '../screens/more/SavedOffersScreen';
import { MyBusinessScreen } from '../screens/more/MyBusinessScreen';
import { PlansScreen } from '../screens/post/PlansScreen';
import { NotificationsScreen } from '../screens/profile/NotificationsScreen';
import { ChatListScreen } from '../screens/profile/ChatListScreen';
import { ChatThreadScreen } from '../screens/profile/ChatThreadScreen';
import { SettingsScreen } from '../screens/profile/SettingsScreen';
import { HelpSupportScreen } from '../screens/profile/HelpSupportScreen';
import { AiAssistantScreen } from '../screens/profile/AiAssistantScreen';
import { LiveLocationScreen } from '../screens/job/LiveLocationScreen';
import { OfferDetailsScreen } from '../screens/offers/OfferDetailsScreen';
import { BusinessDetailsScreen } from '../screens/offers/BusinessDetailsScreen';
import { CreateOfferScreen } from '../screens/post/CreateOfferScreen';
import { BusinessSetupScreen } from '../screens/post/BusinessSetupScreen';
const Stack = createNativeStackNavigator<MoreStackParamList>();
export const MoreNavigator = () => <Stack.Navigator screenOptions={{ headerShown: false }}><Stack.Screen name="MoreHome" component={MoreScreen} /><Stack.Screen name="BusinessCenter" component={BusinessCenterScreen} /><Stack.Screen name="MyBookings" component={MyBookingsScreen as React.ComponentType<any>} /><Stack.Screen name="BookingDetails" component={BookingDetailsScreen as React.ComponentType<any>} /><Stack.Screen name="LiveLocation" component={LiveLocationScreen as React.ComponentType<any>} /><Stack.Screen name="MyOffers" component={MyOffersScreen} /><Stack.Screen name="CreateOffer" component={CreateOfferScreen as React.ComponentType<any>} /><Stack.Screen name="SavedOffers" component={SavedOffersScreen} /><Stack.Screen name="MyBusiness" component={MyBusinessScreen} /><Stack.Screen name="BusinessSetup" component={BusinessSetupScreen as React.ComponentType<any>} /><Stack.Screen name="Plans" component={PlansScreen} /><Stack.Screen name="Notifications" component={NotificationsScreen as React.ComponentType<any>} /><Stack.Screen name="ChatList" component={ChatListScreen as React.ComponentType<any>} /><Stack.Screen name="ChatThread" component={ChatThreadScreen as React.ComponentType<any>} /><Stack.Screen name="Settings" component={SettingsScreen as React.ComponentType<any>} /><Stack.Screen name="HelpSupport" component={HelpSupportScreen as React.ComponentType<any>} /><Stack.Screen name="AiAssistant" component={AiAssistantScreen as React.ComponentType<any>} /><Stack.Screen name="OfferDetails" component={OfferDetailsScreen as React.ComponentType<any>} /><Stack.Screen name="BusinessDetails" component={BusinessDetailsScreen as React.ComponentType<any>} /></Stack.Navigator>;
