import React from 'react';
import { createNativeStackNavigator } from '@react-navigation/native-stack';
import type { ProfileStackParamList } from './types';
import { ProfileScreen } from '../screens/profile/ProfileScreen';
import { EditProfileScreen } from '../screens/profile/EditProfileScreen';
import { SettingsScreen } from '../screens/profile/SettingsScreen';
import { HelpSupportScreen } from '../screens/profile/HelpSupportScreen';
import { FaqScreen } from '../screens/profile/FaqScreen';
import { AiAssistantScreen } from '../screens/profile/AiAssistantScreen';
import { ChatListScreen } from '../screens/profile/ChatListScreen';
import { ChatThreadScreen } from '../screens/profile/ChatThreadScreen';
import { MyBusinessScreen } from '../screens/more/MyBusinessScreen';
import { BusinessSetupScreen } from '../screens/post/BusinessSetupScreen';
import { PlansScreen } from '../screens/post/PlansScreen';
import { SavedOffersScreen } from '../screens/more/SavedOffersScreen';
import { SavedLocationsScreen } from '../screens/profile/SavedLocationsScreen';
const Stack = createNativeStackNavigator<ProfileStackParamList>();
export const ProfileNavigator = () => <Stack.Navigator screenOptions={{ headerShown: false }}><Stack.Screen name="ProfileMain" component={ProfileScreen} /><Stack.Screen name="SavedLocations" component={SavedLocationsScreen} /><Stack.Screen name="EditProfile" component={EditProfileScreen} /><Stack.Screen name="Settings" component={SettingsScreen} /><Stack.Screen name="HelpSupport" component={HelpSupportScreen} /><Stack.Screen name="Faq" component={FaqScreen} /><Stack.Screen name="AiAssistant" component={AiAssistantScreen} /><Stack.Screen name="ChatList" component={ChatListScreen} /><Stack.Screen name="ChatThread" component={ChatThreadScreen} /><Stack.Screen name="MyBusiness" component={MyBusinessScreen} /><Stack.Screen name="BusinessSetup" component={BusinessSetupScreen as React.ComponentType<any>} /><Stack.Screen name="Plans" component={PlansScreen} /><Stack.Screen name="SavedOffers" component={SavedOffersScreen as React.ComponentType<any>} /></Stack.Navigator>;
